---
# role: environment
# file: tasks/main.yml

- name: ENVIRONMENT | Validate configuration
  ansible.builtin.import_tasks: assert.yml

- name: ENVIRONMENT | Configure login environment
  become: true
  become_user: root
  community.general.ini_file:
    path: /etc/environment
    option: "{{ __environment_entry.key }}"
    value: '"{{ __environment_entry.value }}"'
    no_extra_spaces: true
    exclusive: true
    modify_inactive_option: false
    owner: root
    group: root
    mode: "0644"
    backup: true
  loop: "{{ environment_vars | dict2items }}"
  loop_control:
    loop_var: __environment_entry
    label: "{{ __environment_entry.key }}"

- name: ENVIRONMENT | Create drop-in directory
  become: true
  become_user: root
  ansible.builtin.file:
    path: /etc/environment.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: ENVIRONMENT | Configure user-service environment
  become: true
  become_user: root
  ansible.builtin.template:
    src: environment.d.j2
    dest: "/etc/environment.d/{{ __environment_file.name }}"
    owner: root
    group: root
    mode: "0644"
    backup: true
  loop: "{{ environment_d_files }}"
  loop_control:
    loop_var: __environment_file
    label: "{{ __environment_file.name }}"
